# Bad Rollout scenario overlay
# Introduces: Incorrect DATABASE_URL pointing to non-existent host
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-bad-rollout

resources:
  - ../../../base
  - httproute.yaml

patches:
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: fider-env
